DROP TABLE IF EXISTS evento;
DROP TABLE IF EXISTS origem;
DROP TABLE IF EXISTS level;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS authority;
DROP TABLE IF EXISTS user_authority;

CREATE TABLE IF NOT EXISTS origem (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	origem VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS level (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    level VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS evento (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	level INT NOT NULL,
	descricao VARCHAR(255) NOT NULL,
	log VARCHAR(255) NOT NULL,
	origem INTEGER NOT NULL,
	quantidade INTEGER NOT NULL,
	data_criacao DATE NOT NULL,
	hora_criacao TIME NOT NULL,
	data_modificacao DATETIME,
	FOREIGN KEY(origem) REFERENCES origem(id),
	FOREIGN KEY(level) REFERENCES level(id)
);

CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS authority (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_authority (
    user_id INTEGER NOT NULL,
    authority_id INTEGER NOT NULL,
    FOREIGN KEY(user_id) REFERENCES user(id),
    FOREIGN KEY(authority_id) REFERENCES authority(id)
);

